
providers = ["python"]

[variables]
FLASK_ENV = "production"
PORT = "5000"
SESSION_SECRET = "${SESSION_SECRET}"

[phases.setup]
# Pin Python and add system packages
nixPkgs = ["python311", "ffmpeg", "pkg-config"]

[phases.install]
# Install your app (reads pyproject.toml / setup.cfg if present)
cmd = "pip install --no-cache-dir -r requirements.txt"

[phases.build]
# Optional: no build step for a plain Flask app
cmd = "echo 'No build step required'"

[start]
# Make sure the module:app path matches your code (here: main.py defines app)
cmd = "gunicorn --bind 0.0.0.0:${PORT:-5000} --workers 2 --timeout 300 main:app"

[staticAssets]
"/static" = "./static"
